import type { Challenge } from "@/lib/types";

export const challenges: Challenge[] = [
  // Sales
  {
    id: "sales-total-qty",
    domainId: "sales",
    title: "Total Quantity",
    difficulty: "beginner",
    mode: "measure",
    prompt: "Create a measure that returns the total Quantity sold across all orders.",
    hint: "Use SUM on Sales[Quantity].",
    solution: "SUM(Sales[Quantity])",
    explanation: "SUM aggregates a numeric column over the current filter context. With no filters, it totals every row in Sales.",
    expectedValue: 47,
  },
  {
    id: "sales-revenue",
    domainId: "sales",
    title: "Gross Revenue",
    difficulty: "beginner",
    mode: "measure",
    prompt: "Create a measure for revenue before discount: Quantity × UnitPrice, summed across orders.",
    hint: "Use SUMX to iterate Sales and multiply Quantity by UnitPrice.",
    solution: "SUMX(Sales, Sales[Quantity] * Sales[UnitPrice])",
    explanation: "Iterators like SUMX evaluate an expression row by row, then aggregate. This is the classic pattern when revenue is not a stored column.",
    expectedValue: 18400,
  },
  {
    id: "sales-net-revenue",
    domainId: "sales",
    title: "Net Revenue",
    difficulty: "intermediate",
    mode: "measure",
    prompt: "Create net revenue after discount: Quantity × UnitPrice × (1 − Discount).",
    hint: "Extend the SUMX pattern and multiply by (1 - Sales[Discount]).",
    solution: "SUMX(Sales, Sales[Quantity] * Sales[UnitPrice] * (1 - Sales[Discount]))",
    explanation: "Discount is stored as a fraction (0.05 = 5%). Multiplying by (1 − Discount) applies the markdown per line.",
    expectedValue: 17696.25,
    tolerance: 0.1,
  },
  {
    id: "sales-bike-qty",
    domainId: "sales",
    title: "Bike Quantity with CALCULATE",
    difficulty: "intermediate",
    mode: "measure",
    prompt: "Return total Quantity only for products in the Bikes category.",
    hint: "Wrap SUM in CALCULATE and filter Products[Category] = \"Bikes\".",
    solution: 'CALCULATE(SUM(Sales[Quantity]), Products[Category] = "Bikes")',
    explanation: "CALCULATE modifies filter context. Because Sales relates to Products, filtering the category filters the related sales rows.",
    expectedValue: 12,
  },
  {
    id: "sales-line-total-col",
    domainId: "sales",
    title: "Line Total Column",
    difficulty: "beginner",
    mode: "column",
    targetTable: "Sales",
    prompt: "Add a calculated column on Sales that is Quantity × UnitPrice for each row.",
    hint: "In row context you can multiply columns directly — no SUM needed.",
    solution: "Sales[Quantity] * Sales[UnitPrice]",
    explanation: "Calculated columns evaluate in row context. Each Sales row sees its own Quantity and UnitPrice.",
  },
  {
    id: "sales-category-col",
    domainId: "sales",
    title: "Product Category via RELATED",
    difficulty: "intermediate",
    mode: "column",
    targetTable: "Sales",
    prompt: "On Sales, create a column that brings in Products[Category] using RELATED.",
    hint: "RELATED(Products[Category]) follows the many-to-one relationship.",
    solution: "RELATED(Products[Category])",
    explanation: "RELATED pulls a value from the one-side of a relationship into the many-side table’s row context.",
  },
  // HR
  {
    id: "hr-headcount",
    domainId: "hr",
    title: "Active Headcount",
    difficulty: "beginner",
    mode: "measure",
    prompt: "Count employees where Status is Active.",
    hint: "Use CALCULATE with COUNTROWS(Employees) and a Status filter.",
    solution: 'CALCULATE(COUNTROWS(Employees), Employees[Status] = "Active")',
    explanation: "COUNTROWS counts table rows in filter context. CALCULATE narrows to Active employees.",
    expectedValue: 11,
  },
  {
    id: "hr-avg-salary",
    domainId: "hr",
    title: "Average Salary",
    difficulty: "beginner",
    mode: "measure",
    prompt: "Return the average Salary across all employees.",
    hint: "AVERAGE(Employees[Salary])",
    solution: "AVERAGE(Employees[Salary])",
    explanation: "AVERAGE ignores blanks and returns the arithmetic mean of the column.",
    expectedValue: 90583.3333,
    tolerance: 1,
  },
  {
    id: "hr-overtime",
    domainId: "hr",
    title: "Total Overtime Hours",
    difficulty: "beginner",
    mode: "measure",
    prompt: "Sum OvertimeHours from Timesheets.",
    hint: "SUM(Timesheets[OvertimeHours])",
    solution: "SUM(Timesheets[OvertimeHours])",
    explanation: "Simple column aggregation over the timesheet fact table.",
    expectedValue: 26,
  },
  {
    id: "hr-dept-name-col",
    domainId: "hr",
    title: "Department Name Column",
    difficulty: "intermediate",
    mode: "column",
    targetTable: "Employees",
    prompt: "On Employees, add DepartmentName from the Departments table.",
    hint: "RELATED(Departments[DepartmentName])",
    solution: "RELATED(Departments[DepartmentName])",
    explanation: "Employees many → Departments one. RELATED works from the many side.",
  },
  {
    id: "hr-high-earner-col",
    domainId: "hr",
    title: "High Earner Flag",
    difficulty: "intermediate",
    mode: "column",
    targetTable: "Employees",
    prompt: "Create a column that returns \"High\" when Salary >= 100000, otherwise \"Standard\".",
    hint: "Use IF(Employees[Salary] >= 100000, \"High\", \"Standard\").",
    solution: 'IF(Employees[Salary] >= 100000, "High", "Standard")',
    explanation: "IF branches in row context — ideal for classification columns.",
  },
  // Finance
  {
    id: "fin-total-actuals",
    domainId: "finance",
    title: "Total Actuals",
    difficulty: "beginner",
    mode: "measure",
    prompt: "Sum Amount from Actuals.",
    hint: "SUM(Actuals[Amount])",
    solution: "SUM(Actuals[Amount])",
    explanation: "Baseline aggregation for financial actuals.",
    expectedValue: 2948000,
  },
  {
    id: "fin-total-budget",
    domainId: "finance",
    title: "Total Budget",
    difficulty: "beginner",
    mode: "measure",
    prompt: "Sum BudgetAmount from Budgets.",
    hint: "SUM(Budgets[BudgetAmount])",
    solution: "SUM(Budgets[BudgetAmount])",
    explanation: "Budgets live in a separate fact table — aggregate that table’s column.",
    expectedValue: 2860000,
  },
  {
    id: "fin-revenue-actuals",
    domainId: "finance",
    title: "Revenue Actuals",
    difficulty: "intermediate",
    mode: "measure",
    prompt: "Return Actuals Amount only for AccountType = \"Revenue\" (via Accounts).",
    hint: 'CALCULATE(SUM(Actuals[Amount]), Accounts[AccountType] = "Revenue")',
    solution: 'CALCULATE(SUM(Actuals[Amount]), Accounts[AccountType] = "Revenue")',
    explanation: "Filter the dimension; the engine propagates to related Actuals rows.",
    expectedValue: 1783000,
  },
  {
    id: "fin-variance",
    domainId: "finance",
    title: "Actual vs Budget Variance",
    difficulty: "advanced",
    mode: "measure",
    prompt: "Create a variance measure: Total Actuals − Total Budget. You may write it as one expression using both SUMs.",
    hint: "SUM(Actuals[Amount]) - SUM(Budgets[BudgetAmount])",
    solution: "SUM(Actuals[Amount]) - SUM(Budgets[BudgetAmount])",
    explanation: "Variance is often Actual − Budget. Positive means ahead of plan for revenue; interpret carefully for expenses.",
    expectedValue: 88000,
  },
  {
    id: "fin-account-cat-col",
    domainId: "finance",
    title: "Account Category on Actuals",
    difficulty: "intermediate",
    mode: "column",
    targetTable: "Actuals",
    prompt: "On Actuals, bring in Accounts[Category] with RELATED.",
    hint: "RELATED(Accounts[Category])",
    solution: "RELATED(Accounts[Category])",
    explanation: "Denormalizing a category onto the fact table simplifies some visuals — but measures + relationships are often cleaner long-term.",
  },
];

export function getChallengesForDomain(domainId: string) {
  return challenges.filter((c) => c.domainId === domainId);
}

export function getChallenge(id: string) {
  return challenges.find((c) => c.id === id);
}
