import type { Domain } from "@/lib/types";

export const salesDomain: Domain = {
  id: "sales",
  name: "Sales",
  tagline: "Orders, products, and customers",
  description:
    "A classic retail star schema — practice revenue, margins, and customer filters.",
  accent: "#0A6C6D",
  tables: [
    {
      name: "Sales",
      description: "Fact table of order lines",
      isFact: true,
      columns: [
        { name: "OrderID", type: "string" },
        { name: "OrderDate", type: "date" },
        { name: "ProductID", type: "string" },
        { name: "CustomerID", type: "string" },
        { name: "Quantity", type: "number" },
        { name: "UnitPrice", type: "number" },
        { name: "Discount", type: "number", description: "0–1 fraction" },
      ],
      rows: [
        { OrderID: "O1001", OrderDate: "2024-01-05", ProductID: "P01", CustomerID: "C01", Quantity: 2, UnitPrice: 1200, Discount: 0.05 },
        { OrderID: "O1002", OrderDate: "2024-01-08", ProductID: "P02", CustomerID: "C02", Quantity: 1, UnitPrice: 850, Discount: 0 },
        { OrderID: "O1003", OrderDate: "2024-01-12", ProductID: "P03", CustomerID: "C03", Quantity: 4, UnitPrice: 45, Discount: 0.1 },
        { OrderID: "O1004", OrderDate: "2024-02-02", ProductID: "P01", CustomerID: "C02", Quantity: 1, UnitPrice: 1200, Discount: 0 },
        { OrderID: "O1005", OrderDate: "2024-02-14", ProductID: "P04", CustomerID: "C04", Quantity: 3, UnitPrice: 220, Discount: 0.05 },
        { OrderID: "O1006", OrderDate: "2024-02-20", ProductID: "P05", CustomerID: "C01", Quantity: 2, UnitPrice: 65, Discount: 0 },
        { OrderID: "O1007", OrderDate: "2024-03-01", ProductID: "P02", CustomerID: "C05", Quantity: 2, UnitPrice: 850, Discount: 0.1 },
        { OrderID: "O1008", OrderDate: "2024-03-11", ProductID: "P03", CustomerID: "C03", Quantity: 6, UnitPrice: 45, Discount: 0 },
        { OrderID: "O1009", OrderDate: "2024-03-18", ProductID: "P06", CustomerID: "C06", Quantity: 1, UnitPrice: 2400, Discount: 0.08 },
        { OrderID: "O1010", OrderDate: "2024-04-03", ProductID: "P04", CustomerID: "C02", Quantity: 2, UnitPrice: 220, Discount: 0 },
        { OrderID: "O1011", OrderDate: "2024-04-15", ProductID: "P01", CustomerID: "C07", Quantity: 1, UnitPrice: 1200, Discount: 0.05 },
        { OrderID: "O1012", OrderDate: "2024-04-22", ProductID: "P05", CustomerID: "C04", Quantity: 5, UnitPrice: 65, Discount: 0.15 },
        { OrderID: "O1013", OrderDate: "2024-05-06", ProductID: "P06", CustomerID: "C01", Quantity: 1, UnitPrice: 2400, Discount: 0 },
        { OrderID: "O1014", OrderDate: "2024-05-19", ProductID: "P02", CustomerID: "C08", Quantity: 1, UnitPrice: 850, Discount: 0 },
        { OrderID: "O1015", OrderDate: "2024-05-28", ProductID: "P03", CustomerID: "C05", Quantity: 8, UnitPrice: 45, Discount: 0.05 },
        { OrderID: "O1016", OrderDate: "2024-06-04", ProductID: "P04", CustomerID: "C06", Quantity: 2, UnitPrice: 220, Discount: 0.1 },
        { OrderID: "O1017", OrderDate: "2024-06-17", ProductID: "P01", CustomerID: "C03", Quantity: 2, UnitPrice: 1200, Discount: 0 },
        { OrderID: "O1018", OrderDate: "2024-06-25", ProductID: "P05", CustomerID: "C07", Quantity: 3, UnitPrice: 65, Discount: 0 },
      ],
    },
    {
      name: "Products",
      description: "Product dimension",
      columns: [
        { name: "ProductID", type: "string" },
        { name: "ProductName", type: "string" },
        { name: "Category", type: "string" },
        { name: "Cost", type: "number" },
      ],
      rows: [
        { ProductID: "P01", ProductName: "Trail Bike Pro", Category: "Bikes", Cost: 780 },
        { ProductID: "P02", ProductName: "City Hybrid", Category: "Bikes", Cost: 520 },
        { ProductID: "P03", ProductName: "Grip Tape Pack", Category: "Accessories", Cost: 18 },
        { ProductID: "P04", ProductName: "Helmet Apex", Category: "Accessories", Cost: 95 },
        { ProductID: "P05", ProductName: "Water Bottle", Category: "Accessories", Cost: 12 },
        { ProductID: "P06", ProductName: "E-Bike Volt", Category: "Bikes", Cost: 1650 },
      ],
    },
    {
      name: "Customers",
      description: "Customer dimension",
      columns: [
        { name: "CustomerID", type: "string" },
        { name: "CustomerName", type: "string" },
        { name: "City", type: "string" },
        { name: "Region", type: "string" },
        { name: "Segment", type: "string" },
      ],
      rows: [
        { CustomerID: "C01", CustomerName: "Aisha Khan", City: "Austin", Region: "South", Segment: "Consumer" },
        { CustomerID: "C02", CustomerName: "Ben Ortiz", City: "Dallas", Region: "South", Segment: "Corporate" },
        { CustomerID: "C03", CustomerName: "Chen Wei", City: "Seattle", Region: "West", Segment: "Consumer" },
        { CustomerID: "C04", CustomerName: "Dana Lee", City: "Portland", Region: "West", Segment: "Home Office" },
        { CustomerID: "C05", CustomerName: "Elena Rossi", City: "Chicago", Region: "Midwest", Segment: "Corporate" },
        { CustomerID: "C06", CustomerName: "Farid Noor", City: "Denver", Region: "West", Segment: "Consumer" },
        { CustomerID: "C07", CustomerName: "Gina Park", City: "Boston", Region: "East", Segment: "Corporate" },
        { CustomerID: "C08", CustomerName: "Hector Diaz", City: "Miami", Region: "South", Segment: "Home Office" },
      ],
    },
  ],
  relationships: [
    {
      fromTable: "Sales",
      fromColumn: "ProductID",
      toTable: "Products",
      toColumn: "ProductID",
      description: "Many sales lines → one product",
    },
    {
      fromTable: "Sales",
      fromColumn: "CustomerID",
      toTable: "Customers",
      toColumn: "CustomerID",
      description: "Many sales lines → one customer",
    },
  ],
};
